#name: Matrix Node Version Test

on: [push]

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14]
        os: [self-hosted]
        experimental: [false]
        include:
          - node: 18
            os: self-hosted
            experimental: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Show runner info
        run: |
          echo "Running on self-hosted runner"
          echo "OS: ${{ runner.os }}"
          echo "Runner name: ${{ runner.name }}"
          echo "Labels: ${{ runner.labels }}"

      - name: Run custom internal action
        uses: ./my-action

